# autogen-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autogen-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/autogen-data # Ensure this path exists on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - your-node-hostname # Replace with your k3s node hostname
